name: Download a file

on:
  push:
    branches:
      - master
      - main

jobs:
  download-pdf:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          set-safe-directory: 'presslogs'
                
      - name: Download presslog
        uses: valitydev/action-download-file@v1
        with:
            url: https://data.city.ames.ia.us/publicinformation/PressLog.pdf
            target-path: .
            
      - name: Commit result
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add "Presslog*.pdf"
          git commit "*.pdf" -m 'Added presslog' || echo "No changes to commit"
          git push origin || echo "No changes to commit"

