name: Download Presslog

on:
  schedule:
    - cron: "* * * * *"

jobs:
  download-presslog:
    runs-on: ubuntu-latest
    steps:
      - name: Download a file
        uses: valitydev/action-download-file@v1.0.6
        with:
          # URL to file
          url: https://data.city.ames.ia.us/publicinformation/PressLog.pdf
          # Target path
          target-path: presslogs/
        
