name: Download Presslog
on:
  schedule:
    - cron: "0 16 * * *"
    
jobs:
  download-pdf:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          set-safe-directory: 'presslogs'
                
      - name: Download presslog
        uses: valitydev/action-download-file@v1
        with:
            url: https://data.city.ames.ia.us/publicinformation/PressLog.pdf
            target-path: presslogs

      - name: Rename file
        run: |
          datedpdf=$(date "+PressLog-%Y-%m-%d.pdf")
          mv presslogs/PressLog.pdf presslogs/$datedpdf
            
      - name: Commit result
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add presslogs
          git commit "*.pdf" -m 'Added pdf file' || echo "No changes to commit"
          git push origin || echo "No changes to commit"

        
