name: Download Presslog

on:
  schedule:
  - cron: "22 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Download a file
        run: wget -nc -P presslogs/ https://data.city.ames.ia.us/publicinformation/PressLog.pdf
        shell: bash
